apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: huzaifa5/k8s-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_USER
              value: user
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
